[build]
  command = "gem install bundler -v '2.0.2' && python3 -m pip install -U git+https://github.com/ExecutableBookProject/jupyter-book@legacy && jupyter-book build ./ --overwrite && jupyter-book page ./content/features/notebooks.ipynb -o _build && bundle exec jekyll build"
 
